// Generated by https://pagedraw.io/pages/13213
import React from 'react';
import './button.css';


export default class Button extends React.Component {
  render() {
    return (
      <div onClick={this.props.buttonHandler} className="button-button-2">
          <div className="button-0">
              <div className="button-click_-0">Click</div>
          </div>
      </div>
    );
  }
};
