// Generated by https://pagedraw.io/pages/13213
import React from 'react';
import './webframehome.css';


export default class Webframehome extends React.Component {
  render() {
    return (
      <div className="webframehome-webframehome-4">
          <div className="webframehome-0">
              <div className="webframehome-frameshoeshopp-8" /> 
          </div>
          <div className="webframehome-1">
              <div className="webframehome-1-0">
                  <div className="webframehome-1-0-0">
                      <div className="webframehome-frame-2" /> 
                  </div>
              </div>
              <div className="webframehome-1-1">
                  <div className="webframehome-1-1-0">
                      <div className="webframehome-framecard2" /> 
                  </div>
              </div>
          </div>
          <div className="webframehome-2">
              <div className="webframehome-2-0">
                  <div className="webframehome-2-0-0">
                      <div className="webframehome-2-0-0-0">
                          <div className="webframehome-frame_2" /> 
                          <div className="webframehome-all_the_shoes_-5">
                              ALL THE SHOES
                          </div>
                      </div>
                  </div>
              </div>
          </div>
      </div>
    );
  }
};
