// Generated by https://pagedraw.io/pages/13213
import React from 'react';
import './webframeshop.css';


export default class Webframeshop extends React.Component {
  render() {
    return (
      <div className="webframeshop-webframeshop-8">
          <div className="webframeshop-0">
              <div className="webframeshop-frameshoeshopp-4" /> 
          </div>
          <div className="webframeshop-1">
              <div className="webframeshop-1-0">
                  <div className="webframeshop-1-0-0">
                      <div className="webframeshop-frame-5">
                          <div className="webframeshop-1-0-0-0-0">
                              <div className="webframeshop-cardbox-6">
                                  <div className="webframeshop-1-0-0-0-0-0-0">
                                      <img src="https://ucarecdn.com/2c2cb463-5fde-41c0-b070-ca0413d217a5/" className="webframeshop-image_2" /> 
                                  </div>
                                  <div className="webframeshop-1-0-0-0-0-0-1">
                                      <div className="webframeshop-price-8">
                                          <div className="webframeshop-1-0-0-0-0-0-1-0-0">
                                              <div className="webframeshop-_4">$40.00</div>
                                          </div>
                                      </div>
                                  </div>
                                  <div className="webframeshop-1-0-0-0-0-0-2">
                                      <div onClick={this.props.addToCart2} className="webframeshop-button-6">
                                          <div className="webframeshop-1-0-0-0-0-0-2-0-0">
                                              <div className="webframeshop-add_to_cart_-0">
                                                  Add to Cart
                                              </div>
                                          </div>
                                      </div>
                                  </div>
                              </div>
                          </div>
                      </div>
                  </div>
              </div>
              <div className="webframeshop-1-1">
                  <div className="webframeshop-1-1-0">
                      <div className="webframeshop-framecard2">
                          <div className="webframeshop-1-1-0-0-0">
                              <div className="webframeshop-cardbox-1">
                                  <div className="webframeshop-1-1-0-0-0-0-0">
                                      <img src="https://ucarecdn.com/6f1b3d40-0d38-41d0-8418-d82973491d65/" className="webframeshop-image_3" /> 
                                  </div>
                                  <div className="webframeshop-1-1-0-0-0-0-1">
                                      <div className="webframeshop-price-4">
                                          <div className="webframeshop-1-1-0-0-0-0-1-0-0">
                                              <div className="webframeshop-_3">$30.00</div>
                                          </div>
                                      </div>
                                  </div>
                                  <div className="webframeshop-1-1-0-0-0-0-2">
                                      <div onClick={this.props.addToCart} className="webframeshop-button-0">
                                          <div className="webframeshop-1-1-0-0-0-0-2-0-0">
                                              <div className="webframeshop-add_to_cart_-2">
                                                  Add to Cart
                                              </div>
                                          </div>
                                      </div>
                                  </div>
                              </div>
                          </div>
                      </div>
                  </div>
              </div>
          </div>
          <div className="webframeshop-2">
              <div className="webframeshop-frame_2">
                  <div className="webframeshop-2-0-0">
                      <div className="webframeshop-rectangle-9">
                          <div className="webframeshop-2-0-0-0-0">
                              <img src="https://ucarecdn.com/667a0d74-8d9a-42e7-af4c-956d2213aeff/" className="webframeshop-image-6" /> 
                          </div>
                      </div>
                  </div>
                  <div className="webframeshop-2-0-1">
                      <div className="webframeshop-rectangle_2">
                          <div className="webframeshop-2-0-1-0-0">
                              <div className="webframeshop-type_something_-5">
                                  Type something
                              </div>
                          </div>
                      </div>
                  </div>
              </div>
          </div>
      </div>
    );
  }
};
