// Generated by https://pagedraw.io/pages/13213
import React from 'react';
import './webframe.css';


export default class Webframe extends React.Component {
  render() {
    return (
      <div className="webframe-webframe-0">
          <div className="webframe-0">
              <div className="webframe-frameshoeshopp-0">
                  <div className="webframe-0-0-0">
                      <div className="webframe-title-0">
                          <div className="webframe-0-0-0-0-0">
                              <div className="webframe-the_shoes_shopping_store-0">
                                  The Shoes Shopping Store
                              </div>
                          </div>
                      </div>
                  </div>
              </div>
              <div className="webframe-0-1">
                  <div className="webframe-0-1-0">
                      <div className="webframe-0-1-0-0">
                          <div className="webframe-shoesel-0" /> 
                          <div className="webframe-frameshoeselect-0">
                              <div className="webframe-0-1-0-0-1-0">
                                  <div className="webframe-shoe_selections-0">
                                      Shoe Selections
                                  </div>
                              </div>
                          </div>
                      </div>
                  </div>
              </div>
              <div className="webframe-framecheckout-0">
                  <div className="webframe-0-2-0">
                      <div className="webframe-checkout-0">
                          <div className="webframe-0-2-0-0-0">
                              <div className="webframe-cart_checkout-0">
                                  Cart Checkout
                              </div>
                          </div>
                      </div>
                  </div>
              </div>
          </div>
          <div className="webframe-1">
              <div className="webframe-1-0">
                  <div className="webframe-1-0-0">
                      <div className="webframe-frame-0">
                          <div className="webframe-1-0-0-0-0">
                              <div className="webframe-cardbox-0">
                                  <div className="webframe-1-0-0-0-0-0-0">
                                      <img src="https://ucarecdn.com/2c2cb463-5fde-41c0-b070-ca0413d217a5/" className="webframe-image_2" /> 
                                  </div>
                                  <div className="webframe-1-0-0-0-0-0-1">
                                      <div className="webframe-price-0">
                                          <div className="webframe-1-0-0-0-0-0-1-0-0">
                                              <div className="webframe-_4">$40.00</div>
                                          </div>
                                      </div>
                                  </div>
                                  <div className="webframe-1-0-0-0-0-0-2">
                                      <div className="webframe-addtocart-3">
                                          <div className="webframe-1-0-0-0-0-0-2-0-0">
                                              <div className="webframe-add_to_cart-6">Add to Cart</div>
                                          </div>
                                      </div>
                                  </div>
                              </div>
                          </div>
                      </div>
                  </div>
              </div>
              <div className="webframe-1-1">
                  <div className="webframe-1-1-0">
                      <div className="webframe-1-1-0-0">
                          <div className="webframe-framecard2" /> 
                          <div className="webframe-cardbox-00">
                              <div className="webframe-1-1-0-0-1-0">
                                  <img src="https://ucarecdn.com/6f1b3d40-0d38-41d0-8418-d82973491d65/" className="webframe-image_3" /> 
                              </div>
                              <div className="webframe-1-1-0-0-1-1">
                                  <div className="webframe-price-00">
                                      <div className="webframe-1-1-0-0-1-1-0-0">
                                          <div className="webframe-_3">$30.00</div>
                                      </div>
                                  </div>
                              </div>
                              <div className="webframe-1-1-0-0-1-2">
                                  <div className="webframe-addtocart-7">
                                      <div className="webframe-1-1-0-0-1-2-0-0">
                                          <div className="webframe-add_to_cart-69">Add to Cart</div>
                                      </div>
                                  </div>
                              </div>
                          </div>
                      </div>
                  </div>
              </div>
          </div>
          <div className="webframe-2">
              <div className="webframe-frame_2">
                  <div className="webframe-2-0-0">
                      <div className="webframe-rectangle-0">
                          <div className="webframe-2-0-0-0-0">
                              <img src="https://ucarecdn.com/667a0d74-8d9a-42e7-af4c-956d2213aeff/" className="webframe-image-1" /> 
                          </div>
                      </div>
                  </div>
                  <div className="webframe-2-0-1">
                      <div className="webframe-rectangle_2" /> 
                  </div>
              </div>
          </div>
      </div>
    );
  }
};
